import os

import chainlit as cl
from autogen import ConversableAgent

api_key = os.getenv("API_KEY")
if not api_key:
    raise RuntimeError(
        "API_KEY is not set. Set it in the lab .env file before running Docker Compose."
    )

llm_config = {
    "config_list": [
        {
            "model": os.getenv("MODEL", "llama-3.3-70b-versatile"),
            "api_key": api_key,
            "base_url": os.getenv("API_BASE_URL", "https://api.groq.com/openai/v1"),
            "price": [0, 0],
        }
    ],
}

red_team_agent = ConversableAgent(
    name="RedTeamAgent",
    system_message="""\
    You are an expert Red Team attacker. The user will provide a simple Web Application Firewall (WAF) rule.
    Your task is to generate 3 distinct HTTP requests or payloads to test this rule:
    1. Direct Bypass: Try to evade the exact rule using encoding, fragmentation, or alternative syntax.
    2. Different Vector: An attack that doesn't trigger the rule at all (e.g., if the rule blocks SQLi, send an XSS or Path Traversal payload).
    3. False Positive: A completely benign, normal request that might accidentally get blocked by a poorly written rule.
    
    Output ONLY the 3 payloads and a very brief title for each. Do not evaluate the rule yourself.
    """,
    llm_config = llm_config,
    human_input_mode="NEVER",
)

blue_team_agent = ConversableAgent(
    name="BlueTeamAgent",
    system_message="""\
You are an expert Blue Team defender and WAF administrator.
You will receive the user's original WAF rule AND the 3 attack payloads generated by the Red Team.
Analyze each payload against the WAF rule. State clearly whether the rule would SUCCESSFULLY BLOCK or FAIL TO BLOCK each payload.
Finally, provide a brief recommendation to the user on how to improve their WAF rule.
Keep your analysis clear, professional and concise.
""",
    llm_config=llm_config,
    human_input_mode="NEVER",
)


WELCOME_MESSAGE = """\
**Attacker/Defender WAF Simulation Ready!**

Welcome to the Red Team vs Blue Team workflow!
Enter a simple WAF rule (in plain english), and watch the agents battle it out.

**Try these examples:**
- Block any request that contain the words 'script' or 'alert'.
- Drop requests where the URL contains '../' or '..\\'
- Block SQL injection by stopping any request with 'SELECT' or 'UNION'.
"""

def clean_text(text: str) -> str:
    """Remove optional reasoning text returned by some models."""

    if "</think>" in text:
        text = text.split("</think>", 1)[1]
    return text.strip()


def reply_text(reply, fallback: str = "") -> str:
    """Convert an AG2 reply to plain text for display."""

    if reply is None:
        return fallback
    if isinstance(reply, dict):
        reply = reply.get("content", "")
    return clean_text(str(reply)) or fallback


async def ask(agent: ConversableAgent, user_message: str, fallback: str = "") -> str:
    """Ask one agent for one reply."""

    reply = await agent.a_generate_reply(
        messages=[{"role": "user", "content": user_message}]
    )
    return reply_text(reply, fallback)

@cl.on_chat_start
async def start():
    await cl.Message(author="System", content=WELCOME_MESSAGE).send()


@cl.on_message
async def main(message: cl.Message):
    user_waf_rule = message.content

    await cl.Message(author="System", content="Red Team is generating attack payloads...").send()
    red_team_payloads = await ask(red_team_agent, f"User's WAF rule: {user_waf_rule}")

    await cl.Message(author="RedTeamAgent", content=red_team_payloads,).send()

    await cl.Message(author="System", content="Blue Team is evaluating the payloads against the rule...").send()

    blue_team_prompt = f"""Original WAF Rule from User: {user_waf_rule}
    Red Team Payloads: {red_team_payloads}
    
    Please evaluate the rule against these payloads.
    """

    blue_team_analysis = await ask(blue_team_agent, blue_team_prompt)
    await cl.Message(author="BlueTeamAgent", content=blue_team_analysis).send()
